language: nodejs

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - psql -c "CREATE USER haipham;" -U postgres
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm pack